### ISSUE TITLE
1 ms sleep loop

### ISSUE THREAD

**Issue by Machlath** [Jrpl/Bitburner-Scripts#4]
when I start the hack-manager.js it just sleeps for 1 ms in an endless loop. Tried to kill and reset everything but still.

**Comment by SleepyPrince** [comment]
It seems that ns.hackAnalyzeSecurity(hack_threads) returns infinity causing an infinite loop.
Not sure how to fix it.

**Comment by Riley-H-99** [comment]
I looked into it, and what SleepyPrince commented is a potential point of infinite looping. Because there are a couple loops that could cause this, I added a condition that will throw an error and tell us which line it is, if it loops for longer than two minutes. I also changed the increment size of the most common overly long loop that will hopefully speed it up if that was the problem as well. Please try running it with the new commits and let me know what the log says if the problem arises again.

**Comment by Machlath** [comment]
Hey, thanks for the info. There is also an error when no money on the server is that the script is hacking, simply fixed by growing it manually but maybe this can be fixed within the script.

**Comment by Riley-H-99** [comment]
There was another issue that I addressed by changing the script so it no longer adds servers with zero money to be targeted. As far as I know once a server has zero money it can't grow to have any without using the debug console which is why there are so many calculations in the script to ensure that it's impossible to drain a server completely. 

Also well done sending that comment from the moon.

**Comment by syburris** [comment]
Seems to be a sleep issue, initializing grow and weakens on one server then sleeping for 30+ minutes before moving on:

exec: 'targeted-grow.js' on 'pserv-0' with 10333 threads and args: [10333.704137923358, 0, "catalyst"].

exec: 'targeted-weaken.js' on 'pserv-0' with 1727 threads and args: [1727, "catalyst"].

sleep: Sleeping for 2065473.399201595 milliseconds

looking into it

**Comment by Riley-H-99** [comment]
syburris that's intended, it's sleeping for the duration of the targeted-weaken and targeted-grow scripts before continuing to the next part of a series of grows, weakens, and hacks meant to maximize the money made through hacking. As the security level of the targeted server decreases, and as you get a higher hacking level and augments, the overall time for everything will decrease. 30 minutes is within reason and should be the most time efficient method of hacking for your current stats.

> Seems to be a sleep issue, initializing grow and weakens on one server then sleeping for 30+ minutes before moving on:
> 
> exec: 'targeted-grow.js' on 'pserv-0' with 10333 threads and args: [10333.704137923358, 0, "catalyst"].
> 
> exec: 'targeted-weaken.js' on 'pserv-0' with 1727 threads and args: [1727, "catalyst"].
> 
> sleep: Sleeping for 2065473.399201595 milliseconds
> 
> looking into it

**Comment by syburris** [comment]
understood, just found this yesterday and haven't read through everything yet, seemed like different behavior from previous commit so I thought it was an accidental loop, sorry!
